### PR TITLE
Adds support for Swedish characters å, ä and ö

### PR DESCRIPTION
**Pull request by alexanderwallin**

### CODE REVIEW

**Comment by tunnckoCore** [comment]
cool

**Comment by tunnckoCore** [comment]
i will publish from the desktop

**Comment by tunnckoCore** [comment]
actually, @jonschlinkert need to publish ;d i don't have npm access

**Comment by jonschlinkert** [comment]
you now have publish rights! sorry about that!

**Comment by tunnckoCore** [comment]
Cool, thanks. No problem.

edit: @alexanderwallin it is 0.1.2 now, thanks for the PR.

**Comment by alexanderwallin** [comment]
My pleasure!

**Pull request merged**
