### PR TITLE
Contractions and Armenian

### LINKED ISSUE #6: Contractions
The regex doesn't account for contractions. Is there any reason not to add apostrophes to the expression?

For instance:

``The regex doesn't account for contractions.`` counts as seven words, but should be six.

### PR DESCRIPTION
**Pull request by davidlday**
* Closes #6 - now counts contractions in English as a single word
* Added support for Armenian character set

Changes came from discussions and changed on the [atom-wordcount](https://github.com/OleMchls/atom-wordcount) package.

### CODE REVIEW

**Comment by tunnckoCore** [comment]
Thanks.

Hm. @jonschlinkert i can't publish, but seems like included in the npm page as publisher? huh :D 

Just need `npm publish`, i've done the rest - v0.1.3

**Comment by doowb** [comment]
@olstenlarck I just talked to @jonschlinkert about this and we'll try to get it published soon. Maybe there was an NPM issue earlier so you could try again.

**Comment by jonschlinkert** [comment]
Yeah we’ll make sure you’re added to NPM

**Comment by tunnckoCore** [comment]
Hm. Stil nah... 

```
~/tunnckoCore/word-regex master 
❯ npm publish
npm notice 
npm notice 📦  word-regex@0.1.3
npm notice === Tarball Contents === 
npm notice 1.2kB package.json
npm notice 510B  index.js    
npm notice 1.1kB LICENSE     
npm notice 3.1kB README.md   
npm notice === Tarball Details === 
npm notice name:          word-regex                              
npm notice version:       0.1.3                                   
npm notice package size:  2.5 kB                                  
npm notice unpacked size: 6.0 kB                                  
npm notice shasum:        1637b8c18d57892b01856b5592c249ad3aa22a47
npm notice integrity:     sha512-8bTC7IDuGftCL[...]beqX/ciQjNP2Q==
npm notice total files:   4                                       
npm notice 
npm ERR! publish Failed PUT 403
npm ERR! code E403
npm ERR! You do not have permission to publish "word-regex". Are you logged in as the correct user? : word-regex

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/charlike/.npm/_logs/2018-09-12T21_35_48_395Z-debug.log

```

It shows on my avatar that it is `~tunnckocore` but is it that way really? Cuz i was changing the names and recently i back to `tunnckocore`.

**Pull request merged**
